# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  PORT: '3000'
  DATABASE_URL: '$(DATABASE_URL)'  # Set securely in Azure DevOps pipeline variables or variable group
  API_KEY: '$(API_KEY)'            # Secrets should be defined securely in Azure DevOps

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    echo "Creating .env file..."
    echo "PORT=${PORT}" > .env
    echo "DATABASE_URL=${DATABASE_URL}" >> .env
    echo "API_KEY=${API_KEY}" >> .env
  displayName: 'Generate .env file'

- script: |
    npm install --legacy-peer-deps
  displayName: 'Install dependencies'

- script: |
    npm run build
  displayName: 'Build app'